name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: |
        sudo apt-get install clang
        sudo apt-get install --no-install-recommends libasio-dev
      
    - name: Install dependencies
      run: make TARGET_ARCH=arm
      
    - uses: actions/upload-artifact@v2
      with:
        name: root
        path: .
